#pragma once

#define CMD_LED_ON 0x1
#define CMD_LED_OFF 0x2
#define CMD_LED_SET 0x3
#define CMD_LED_SET_ROW 0x4
#define CMD_LED_SET_PROFILE 0x5
#define CMD_LED_NEXT_PROFILE 0x6
#define CMD_LED_PREV_PROFILE 0x7
#define CMD_LED_GET_PROFILE 0x8
#define CMD_LED_GET_NUM_PROFILES 0x9
#define CMD_LED_SET_MASK 0xA
#define CMD_LED_CLEAR_MASK 0xB
#define CMD_LED_NEXT_INTENSITY 0xC
#define CMD_LED_NEXT_ANIMATION_SPEED 0xD
#define CMD_LED_SET_FOREGROUND_COLOR 0xE
#define CMD_LED_CLEAR_FOREGROUND_COLOR 0xF
#define CMD_LED_IAP 0x10
#define CMD_LED_KEYPRESS 0x11
